/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TD2;

import Tools.Tools;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author florian
 */
public class Exercice3 extends javax.swing.JFrame {

    /**
     * Creates new form Exercice3
     */
    public Exercice3() {
        initComponents();
        Tools.windowsInit(this);
        initCpt();
        afficheCpt();
        etat = State.Init;
        presentationInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAffichage = new javax.swing.JLabel();
        buttonUp = new javax.swing.JButton();
        buttonDown = new javax.swing.JButton();
        buttonStart = new javax.swing.JButton();
        buttonStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelAffichage.setText("jLabel1");

        buttonUp.setText(">>");
        buttonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpActionPerformed(evt);
            }
        });

        buttonDown.setText("<<");
        buttonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDownActionPerformed(evt);
            }
        });

        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        buttonStop.setText("Stop");
        buttonStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelAffichage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonDown, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(buttonUp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(174, 174, 174)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAffichage, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonUp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDown, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonStop, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
        switch (etat) {
            case Init:
                etat = State.Avance;
                initCpt();
                afficheCpt();
                presentationUp();
                break;
            case Avance:
                //Interdit
                break;
            case Recule:
                //Interdit
                break;

        }
    }//GEN-LAST:event_buttonStartActionPerformed

    private void buttonStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopActionPerformed
        switch (etat) {
            case Init:
                //Interdit
                break;
            case Avance:
                etat = State.Init;
                initCpt();
                afficheChaine("Pouf");
                presentationInit();
                break;
            case Recule:
                etat = State.Init;
                initCpt();
                afficheChaine("Pouf");
                presentationInit();
                break;

        }
    }//GEN-LAST:event_buttonStopActionPerformed

    private void buttonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDownActionPerformed
        switch (etat) {
            case Init:
                //Interdit
                break;
            case Avance:
                etat = State.Recule;
                egalCpt();
                afficheCpt();
                presentationDown();
                break;
            case Recule:
                //Interdit
                break;

        }
    }//GEN-LAST:event_buttonDownActionPerformed

    private void buttonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpActionPerformed
        switch (etat) {
            case Init:
                //Interdit
                break;
            case Avance:
                //Interdit
                break;
            case Recule:
                etat = State.Avance;
                egalCpt();
                afficheCpt();
                presentationUp();
                break;

        }
    }//GEN-LAST:event_buttonUpActionPerformed
    private void tickTimerUpActionPerformed(java.awt.event.ActionEvent e) {
        switch (etat) {
            case Init:
                //Interdit
                break;
            case Avance:
                if (cpt < 15) {
                    etat = State.Avance;
                    incrementCpt();
                    afficheCpt();
                    presentationUp();
                } else {
                    etat = State.Init;
                    afficheCpt();
                    presentationInit();
                }
                break;
            case Recule:
                //Interdit
                break;

        }
    }

    private void tickTimerDownActionPerformed(java.awt.event.ActionEvent e) {
        switch (etat) {
            case Init:
                //Interdit
                break;
            case Avance:
                //Interdit
                break;
            case Recule:
                if (cpt > 0) {
                    etat = State.Recule;
                    decrementCpt();
                    afficheCpt();
                    presentationDown();
                } else {
                    etat = State.Init;
                    afficheCpt();
                    presentationInit();
                }
                break;

        }
    }

    private void afficheCpt() {
        labelAffichage.setText(String.valueOf(cpt));
    }

    private void afficheChaine(String chaine) {
        labelAffichage.setText(chaine);
    }

    private void initCpt() {
        cpt = 0;
    }

    private void incrementCpt() {
        cpt++;
    }

    private void decrementCpt() {
        cpt--;
    }

    private void egalCpt() {
        cpt = cpt;
    }

    private void presentationInit() {
        Tools.desactiverBoutton(buttonDown, buttonUp, buttonStop);
        Tools.activerBoutton(buttonStart);
        timerUp.stop();
        timerDown.stop();
    }

    private void presentationDown() {
        Tools.activerBoutton(buttonUp, buttonStop);
        Tools.desactiverBoutton(buttonDown, buttonStart);
        timerUp.stop();
        timerDown.start();
    }

    private void presentationUp() {
        Tools.desactiverBoutton(buttonUp, buttonStart);
        Tools.activerBoutton(buttonDown, buttonStop);
        timerUp.start();
        timerDown.stop();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercice3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercice3().setVisible(true);
            }
        });
    }
    private State etat;
    private int cpt;
    private final Timer timerDown = new Timer(500, (ActionEvent e) -> {
        tickTimerDownActionPerformed(e);
    });
    private final Timer timerUp = new Timer(500, (ActionEvent e) -> {
        tickTimerUpActionPerformed(e);
    });

    private enum State {
        Init, Avance, Recule;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDown;
    private javax.swing.JButton buttonStart;
    private javax.swing.JButton buttonStop;
    private javax.swing.JButton buttonUp;
    private javax.swing.JLabel labelAffichage;
    // End of variables declaration//GEN-END:variables
}
